In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Read in the data
abortion_and_health = pd.read_csv('./clean_datasets/abortion_and_health.csv')
domestic_violence = pd.read_csv('./clean_datasets/domestic_violence.csv')
gdi_year_schooling = pd.read_csv('./clean_datasets/gdi_year_schooling.csv')
unpaid_work = pd.read_csv('./clean_datasets/upaid_work.csv')
gender_paygap = pd.read_csv('./clean_datasets/gender-pay-gap-US-2014.csv')

In [5]:
abortion_and_health.describe()

,"Average annual % of all pregnancies ending in abortion, 2015-2019 [9]","Average annual no. of pregnancies per 1,000 women aged 15–49, 2015-2019 [9]","Average annual no. of intended pregnancies per 1,000 women aged 15–49, 2015-2019 [9]","Average annual no. of planned births per 1,000 women aged 15–49, 2015-2019 [9]","Average annual no. of unintended pregnancies per 1,000 women aged 15–49, 2015-2019 [9]","Average annual % pregnancies unintended, 2015-2019 [9]","Average annual no. of unplanned births per 1,000 women aged 15–49, 2015-2019 [9]","Average annual % of unintended pregnancies ending in abortion, 2015-2019 [9]","Average annual no. of abortions per 1,000 women aged 15–49, 2015-2019 [9]"
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,25.225806,138.354839,73.193548,60.967742,65.354839,48.096774,23.548387,52.903226,33.548387
std,7.710208,48.995611,33.445896,27.825029,21.429805,9.414014,13.681712,13.407348,10.990416
min,13.000000,61.000000,36.000000,30.000000,24.000000,27.000000,4.000000,31.000000,9.000000
25%,20.000000,107.500000,45.000000,37.000000,52.000000,43.000000,12.500000,42.500000,30.000000
50%,23.000000,129.000000,66.000000,55.000000,65.000000,47.000000,22.000000,50.000000,35.000000
75%,31.500000,170.000000,91.000000,76.000000,81.000000,52.500000,32.500000,64.500000,42.000000
max,43.000000,251.000000,155.000000,129.000000,107.000000,67.000000,59.000000,80.000000,56.000000

In [6]:
domestic_violence.describe()

         Year       Value
count   164.0  164.000000
mean   2018.0   26.275378
std       0.0    9.751725
min    2018.0   10.000000
25%    2018.0   19.000000
50%    2018.0   24.000000
75%    2018.0   32.047314
max    2018.0   53.000000

In [7]:
gdi_year_schooling.describe()

,GDI,Expected Year of Schooling-Female,Expected Year of Schooling-Male,Mean Year of Schooling-Female,Mean Year of Schooling-Male
count,172.000000,172.000000,172.000000,172.000000,172.000000
mean,0.947285,13.856395,13.495349,8.741279,9.273837
std,0.065906,3.271213,2.627671,3.516990,2.973167
min,0.496000,4.500000,6.600000,1.300000,2.200000
25%,0.920000,11.800000,11.900000,5.675000,6.800000
50%,0.967000,14.050000,13.550000,9.450000,9.400000
75%,0.989000,16.200000,15.325000,11.700000,11.800000
max,1.034000,21.800000,20.300000,13.900000,14.300000

In [8]:
unpaid_work.describe()

         Time       Value
count   204.0  204.000000
mean   2021.0  312.008824
std       0.0  132.474469
min    2021.0   40.800000
25%    2021.0  208.800000
50%    2021.0  289.300000
75%    2021.0  440.575000
max    2021.0  609.800000

In [9]:
gender_paygap.describe()

,Women average annual salary ($),Men average annual salary ($),Pay gap ($)
count,80.000000,80.000000,80.000000
mean,41102.475000,51836.475000,10733.962500
std,15827.119636,22187.107907,8431.118953
min,19188.000000,19968.000000,0.000000
25%,27001.000000,32760.000000,4342.000000
50%,38506.000000,48490.000000,9334.000000
75%,51974.000000,64974.000000,13949.000000
max,82680.000000,116792.000000,39728.000000

In [3]:
unpaid_work = pd.pivot_table(unpaid_work, values='Value', index=['COU', 'Country', 'Age Group', 'Time', 'Unit Code'], columns=['Indicator', 'SEX'])
unpaid_work.columns = ['_'.join(col).strip() for col in unpaid_work.columns.values]
unpaid_work

,,,,,"Time spent in paid work, by sex_MEN","Time spent in paid work, by sex_WOMEN","Time spent in total work, by sex_MEN","Time spent in total work, by sex_WOMEN","Time spent in unpaid work, by sex_MEN","Time spent in unpaid work, by sex_WOMEN"
COU,Country,Age Group,Time,Unit Code,,,,,,
AUS,Australia,15-64,2021,MPD,304.1,172.0,475.7,483.0,171.6,311.0
AUT,Austria,15-64,2021,MPD,364.8,248.8,500.1,517.9,135.3,269.2
BEL,Belgium,15-64,2021,MPD,273.7,199.2,417.9,436.6,144.2,237.3
CAN,Canada,15-64,2021,MPD,340.5,268.3,488.7,491.9,148.1,223.7
CHN,China (People's Republic of),15-64,2021,MPD,390.0,291.0,481.0,525.0,91.0,234.0
DEU,Germany,15-64,2021,MPD,289.5,205.5,440.0,447.7,150.4,242.3
DNK,Denmark,15-64,2021,MPD,260.1,194.6,446.2,437.4,186.1,242.8
ESP,Spain,15-64,2021,MPD,236.2,166.8,382.1,455.9,145.9,289.1
EST,Estonia,15-64,2021,MPD,264.1,244.9,424.2,494.1,160.2,249.2
FIN,Finland,15-64,2021,MPD,248.6,209.9,406.0,445.7,157.5,235.8
FRA,France,15-64,2021,MPD,235.1,175.4,370.1,399.4,134.9,224.0
GBR,United Kingdom,15-64,2021,MPD,308.6,216.2,448.7,464.8,140.1,248.6
GRC,Greece,15-64,2021,MPD,274.3,184.5,369.4,444.0,95.1,259.5
HUN,Hungary,15-64,2021,MPD,272.7,202.5,435.0,496.3,162.3,293.8
IND,India,15-64,2021,MPD,390.6,184.7,442.3,536.6,51.8,351.9
IRL,Ireland,15-64,2021,MPD,340.8,194.9,467.8,487.4,127.0,292.5
ITA,Italy,15-64,2021,MPD,220.8,133.1,351.5,439.5,130.7,306.3
JPN,Japan,15-64,2021,MPD,451.8,271.5,492.6,495.8,40.8,224.3
KOR,Korea,15-64,2021,MPD,419.0,269.4,468.0,484.4,49.0,215.0
LTU,Lithuania,15-64,2021,MPD,354.3,279.3,505.9,571.2,151.6,292.0
LUX,Luxembourg,15-64,2021,MPD,330.0,238.9,451.1,478.5,121.1,239.6
LVA,Latvia,15-64,2021,MPD,376.9,288.5,506.7,541.7,129.7,253.3
MEX,Mexico,15-64,2021,MPD,478.3,236.3,609.8,567.6,131.4,331.3
NLD,Netherlands,15-64,2021,MPD,284.9,201.4,430.4,426.4,145.4,224.9
NOR,Norway,15-64,2021,MPD,277.4,200.0,445.9,427.4,168.5,227.4
NZL,New Zealand,15-64,2021,MPD,338.0,205.0,479.0,469.0,141.0,264.0
OAVG,OECD - Average,15-64,2021,MPD,317.8,217.7,454.3,481.1,136.5,263.4
POL,Poland,15-64,2021,MPD,314.8,203.2,473.6,498.2,158.8,295.0
PRT,Portugal,15-64,2021,MPD,372.3,231.3,468.6,559.4,96.3,328.2
SVN,Slovenia,15-64,2021,MPD,299.8,234.2,466.3,520.4,166.5,286.2
SWE,Sweden,15-64,2021,MPD,313.0,275.2,484.0,495.3,171.0,220.2
TUR,Türkiye,15-64,2021,MPD,358.3,133.9,425.8,439.0,67.6,305.0
USA,United States,15-64,2021,MPD,331.7,247.0,497.6,518.3,165.8,271.3
ZAF,South Africa,15-64,2021,MPD,294.2,195.0,397.1,444.6,102.9,249.6

In [4]:
unpaid_work.to_csv('./clean_datasets/unpaid_work.csv', index=True)

In [4]:
domestic_violence = domestic_violence[domestic_violence['Year'] == 2018]
domestic_violence = domestic_violence.drop_duplicates(subset='Country Name', keep='first')
domestic_violence.to_csv('./clean_datasets/domestic_violence.csv', index=False)